name: rio-hist-dev
channels:
  - conda-forge
dependencies:
  - python =3.12
  - pip
  # required
  - click
  - matplotlib
  - numpy
  - rasterio
  - rio-mucho
  # testing
  - pytest
  - pytest-cov
  # linting
  - pre-commit
  - ruff ==0.11.6
  - pip:
    - rio-color